baseURL = 'https://jhuizinga.github.io/github.io/'
languageCode = 'ja-jp'
title = 'Arisaka Dynasty'
theme = "beautifulhugo"



[Author]
name = "Uyu"
twitter = "megalorrountas"
mastodon = "mstdn.maud.io/web/@uyu"

[params]
subtitle = "Yatte!"
showRSSButton = false
fadeIn = false
dateFormat = "2006/01/02"
#email = "asojae1894@gmail.com"
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  delayDisqus = true

[params.home]
localTime = true
timeZone = "Asia/Tokyo"
timeFormat = "ja-JP"

[params.share]
twitter = true
facebook = true


[[menu.main]]
    name = "Blog"
    url = "blog/"
    weight = 6

[[menu.main]]
    identifier = "Arisaka"
    name = "About"
    weight = 1

[[menu.main]]
    parent = "Arisaka"
    name = "About"
    url = "/about/"
    weight = 1

[[menu.main]]
    parent = "Arisaka"
    name = "ラーメン同好会"
    url = "ramen/"
    weight = 2


[[menu.main]]
    url = "member/"
    name = "Members"
    weight = 2

[[menu.main]]
    identifier = "Achievements"
    name = "Achievements"
    weight = 4

[[menu.main]]
    parent = "Achievements"
    name = "宇高英語部"
    url = "/achievements/"
    weight = 1

[[menu.main]]
    parent = "Achievements"
    name = "OB"
    url = "/ob/"
    weight = 2

[[menu.main]]
    name = "Support"
    url = "/support/"
    weight = 5

[[menu.main]]
    name = "Almuni"
    url = "/almuni/"
    weight = 10


[markup.goldmark.renderer]
      unsafe = true



    


