baseURL = 'https://JHuizinga/github.io/'
languageCode = 'en'
title = 'Arisaka Dynasty'
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[Author]
twitter = "englishUTKdeba"
instagram = "utk_englishdebate"

[params]
subtitle = "YATTE!"
showRSSButton = false
fadeIn = false
dateFormat = "2006/01/02"
#email = ""
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  socialShare = true
  delayDisqus = true

[params.home]
localTime = true
timeZone = "Asia/Tokyo"
timeFormat = "ja-JP"

[params.share]
twitter = true
facebook = true


[[menu.main]]
    name = "Blog"
    url = ""
    weight = 3

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1

[[menu.main]]
    identifier = "samples"
    name = "Members"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Current"
    url = "currentgeneration"
    weight = 1

[[menu.main]]
    parent = "samples"
    name = "OB"
    url = "OB"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Educator"
    url = "educator"
    weight = 3

[[menu.main]]
    name = "Support"
    url = "support"
    weight = 3

[[menu.main]]
    name = "Achievement"
    url = "achievement"
    weight = 4
