baseURL = 'https://jhuizinga.github.io/github.io/'
languageCode = 'ja-jp'
title = 'Arisaka Dynasty'
theme = "beautifulhugo"


[Author]
twitter = "megalorrountas"
mastodon = "mstdn.maud.io/web/@uyu"

[params]
subtitle = "Yatte!"
showRSSButton = false
fadeIn = false
dateFormat = "2006/01/02"
#email = "asojae1894@gmail.com"
  comments = true
  readingTime = true
  wordCount = true
  useHLJS = true
  delayDisqus = true

[params.home]
localTime = true
timeZone = "Asia/Tokyo"
timeFormat = "ja-JP"

[params.share]
twitter = true
facebook = true


[[menu.main]]
    name = "Blog"
    url = "page/blog/"
    weight = 6

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1

[[menu.main]]
    url = "page/member/"
    name = "Members"
    weight = 2

[[menu.main]]
    name = "Support"
    url = "page/support/"
    weight = 3

[[menu.main]]
    name = "Achievements"
    url = "page/achievements/"
    weight = 4


   


