baseURL = 'https://JHuizinga/github.io/'
languageCode = 'ja-jp'
title = 'Arisaka Dynasty'
theme = "beautifulhugo"

[Author]
twitter = "englishUTKdeba"
instagram = "username"

[params]
themeStyle = "auto"
subtitle = "YATTE!"
showRSSButton = false
fadeIn = false
dateFormat = "2006/01/02"
#email = ""

[params.home]
localTime = true
timeZone = "Asia/Tokyo"
timeFormat = "ja-JP"

[params.share]
twitter = true
facebook = true


[[menu.main]]
    name = "Blog"
    url = ""
    weight = 3

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 1

[[menu.main]]
    identifier = "samples"
    name = "Members"
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Current"
    url = ""
    weight = 1

[[menu.main]]
    parent = "samples"
    name = "OB"
    url = ""
    weight = 2

[[menu.main]]
    parent = "samples"
    name = "Educator"
    url = "post/2016-03-08-code-sample"
    weight = 3

[[menu.main]]
    name = "Support"
    url = "tags"
    weight = 3

[[menu.main]]
    name = "Achievement"
    url = "tags"
    weight = 4
